export default [
    "Somalisch handje, alles proper maken",
    "Lichtfestival Gent",
    "Haartransplantatie",
    "Veel duiven gevangen (Antwerpen, Beveren, Holland)",
    "Cherinataart",
    "Giethoorn + scooter",
    "Racist op parking",
    "Lenteui",
    "Ambulance meegereden",
    "Lopen voor je hart bij Chardome",
    "Wij gaan joggen",
    "Plakkeplak in het bed, ik pak je laken weg voor afkoeling",
    "HUNGURI, klinkt dat echt zo Afrikaans?",
    "De keer dat we geen pizza gingen eten was je zo lief triest",
    "Handjes voor jouw ogen bij dirty talk",
    "Ons laten masseren. Pijnlijk en gelachen",
    "Fais quelque chose!",
    "Benen omhoog in bed",
    "Altijd op aren omhoog bij positieswitch",
    "Duitsland Moezel",
    "Sumaya on board-sticker",
    "Vrouwencondoom",
    "Blauw-witte schoentjes",
    "Jij bent niet mijn aabe",
    "Kloostertraat van balkon gevallen. Ik grijp jouw nek",
    "Het is een nacht (liedje)",
    "Krulletjes als je moe bent",
    "Plakkeplak",
    "'s Nachts trek ik jouw laken weg",
    "Doesa's die je 's nachts laat",
    "Ik kom bij jou liggen in bed en in de zetel toen je aan jouw knie geopereerd was",
    "Op mijn lippen bijten als ze jou meenemen naar de operatiezaal of toen je jouw moeder zag",
    "Ik kijk 's nachts naar jou als je slaapt (op een niet freaky manier :D)",
    "Ik lig bijna OP jou als je slaapt",
    "De beeeed",
    "Ik spring altijd naar jou als ik een nachtmerrie heb. Jij schudt me wakker.",
    "Samen spreekbeurten geven",
    "Poolen, bowlen, lunaparkten met die schijf",
    "Naaien",
    "Ik die tabak drink in de auto",
    "Jouw Engelse ingesproken teksten voor school",
    "Alles voor jouw auto, radio, pinkers, auto simoniseren twee dagen, band vervangen, ...",
    "Je m'appelle, je suis Sumaya",
    "Samen zoveel Vlaamse series ontdekt",
    "Ijspaleis Antwerpen Zuid",
    "Absolute stilte, geen gemaar",
    "Kom es hier, kom es daar. Wie is wie, wie is waar?",
    "Tongetje in de mond, knip knip",
    "Een, er",
    "Bellen tijdens pauze",
    "Flandria",
    "Spoed na pita babysit Sarah",
    "Sint-Niklaas, Leuven, Brussel, Gent, Oostende, Antwerpen, Hasselt, ...",
    "Krulletjes overal in huis",
    "Weekendjes weg met mijn moeder en daar fietsen, zwemmen, ...",
    "Wuiven tot op de parking van Colruyt",
    "Notebook gezien en jij wenen",
    "Betrappen op in slaap vallen voor gsm",
    "Jouw Eddy Murphy smile, tijdens het zwemmen met Peter en Nasteeha, toen ik jou als een plank vastnam.",
    "Hartje in de spinazie of puree",
    "Bicky met varken per ongeluk gegeten",
    "Lolly krijgen bij frietChinees",
    "Om ter snelst laken insteken",
    "Somalisch praten in jouw slaap",
    "Nieuwjaar bij Peter en Nasteeha. Zij sliepen al ... .",
    "Aan jouw tepel komen",
    "Jouw borsten platduwen om jou te plagen",
    "Shoppen in Maasmechelen, Rosendaal, Wijnegem, Meir, ...",
    "Jouw chique schoentjes",
    "Danza Kuduro. Jij bent dat meisje als we de lotto winnen",
    "Huizen in Schilde zien. Beide triest en grappig",
    "Stoppen met schattig zijn, want ik zal je pakken zenne!",
    "Stront in zwembad",
    "Zelfgemaakte Mojito",
    "Voeten in vissenbadje doen",
    "Jouw moeder en alle vrienden leren kennen",
    "In jouw armen liggen in de zetel",
    "Naar locaties van Thuis gaan kijken",
    "Mamadora zingen samen",
    "Ondersteboven, binnenstebuiten",
    "Vroeger, te vroeg",
    "Mijn oren kuisen",
    "Te dikke boterhammen gemaakt",
    "Samen puzzelen",
    "Samen voetballen tijdens weekend",
    "Jij danst Michael Jackson",
    "Met de step gaan rijden",
    "I wanna wake up with you (liedje)",
    "STILL KALM ALLEZ STILL KALM",
    "Samen gestopt met roken",
    "In the middle of the night (liedje)",
    "Axxess Café",
    "Jou Nederlands leren",
    "5 jaar samen naar school geweest",
    "Samen gaan solliciteren bij Tom Lidl",
    "Helpen behangen, schilderen",
    "\"Es\" is ons woordje door jou uitgevonden",
    "Bloementapijt Brussel",
    "Jij verkeerd gereden naar Brussel ipv Leuven",
    "Samen start to run gedaan, maar lukte langs geen kanten",
    "Mariam en Fifi in Antwerpen",
    "Gangam style van Saber",
    "Jij en Mariam bang in dat gele tuig in de kinderspeeltuin",
    "Jouw familie bezocht in Zweden en lachen hoe slecht Zweden wel is",
    "Bart en Evelyne leren kennen",
    "Goedroen leren kennen",
    "Naar het vastgelopen schip gaan zien in Nederland",
    "Sinterklaas is geweest voor jou",
    "Naar verschillende trouwfeesten geweest met jou. Met jouw te korte jurkje door mijn schuld",
    "Jouw Excelarmpjes die me wegduwen",
    "Lachen met jouw Frank Spencer moves",
    "Samen met Dany de Punto gaan kopen",
    "De gay pride 2x gezien",
    "Met de kindjes van Sarah naar pretparken en K3",
    "Kreta (jouw eerste toeristische reis en ook die van ons samen) en Frankrijk",
    "Gaan wendelen in Stabroek tussen de bomen en aan het meer",
    "Naar de shopping in Duitsland",
    "Etentjes bij mama en papa",
    "Nasteha en Peter leren kennen",
    "jij mijn hele familie leren kennen en zij houden van jou",
    "Valentijn dikwijls gevierd",
    "Verjaardagen gevierd met vele taarten",
    "Nieuwjaarsavonden tot een stuk in de nacht, tot we ouder en snel moe werden.",
    "Kerstfeestjes bij familie",
    "Zovele dokters samen bezocht op zoek naar jouw pijnoorzaken",
    "Met de tanden door de Kalmthoutse Heide",
    "Leren autorijden. Gas geven godverdomme!",
    "Leren zwemmen. 25 meter behaald",
    "2022, het jaar van 100 ijsjes eten",
    "Leren rekenen",
    "De kerstmarkten in Antwerpen",
    "Bobbejaandland als tweede date. Daar kuste ik jou voor het eerst in het reuzenrad",
    "Samen de kerstboom opstellen",
    "Naar Pairi Daiza geweest en de te kleine panda's gezien",
    "De shopping, onze tweede thuis",
    "Pokemon gaan zoeken in Lillo",
    "Vandalisme op auto's in de stad. Vooral jij schopte op de wagens",
    "Belleke trek doen in het midden van de nacht",
    "10 lessen Salsa gedaan. En dan konden we goed!",
    "Gaan dansen in de Noxx als een bezeten freak",
    "Gaan waterfietsen op de Ster",
    "Vele keren minigolf",
    "Honderden pizza's bbq chicken gegeten",
    "Naar modemuseum geweest en wij waren de zoveelste bezoeker en kregen boeken",
    "Naar de Red Star Line geweest",
    "Zalige zonnige dagjes naar Antwerpen gegaan. Samen de stad blijven ontdekken. Dankzij jou verliefd geworden op Antwerpen",
    "Naar het Mas gegaan.",
    "Naar het mooie Lier gegaan maar niemand deed open in het klooster. We liepen er ook om ter snelst.",
    "Om ter snelst naar boven op de trap in Stabroek. Ik kan jou nooit pakken.",
    "Ik altijd blij als een hondje als je thuiskomt! Steeds een kusje bij ontvangst en jij ook",
    "Altijd wuiven aan het raam als iemand vertrekt naar het werk. Zelfs de buren wuifden mee op den duur.",
    "Dat skateboard dat op jouw gezicht viel. Zo erg",
    "Ook toen je viel met de fiets tegen het verkeerslicht en dan naar de dokter van wacht.",
    "Jij die eens met mijn auto mag rijden in de haven en volle gas gaf ipv remmen!",
    "Wij die elkaar -om te lachen- telkens de schuld geven",
    "'s Nachts hard bonken in de Kloosterstraat. Daar is meer hout dan hier in dit huis. Ik denk dat heel de blok het gehoord heeft.",
    "Zatte terrasjes gedaan en lekker veel roken",
    "Sauna's gedaan en jij bang in het ondiepe water",
    "Naar de zee, jij onder de parasol, verlegen in jouw eerste groene bikini",
    "Naar de Ardennen. Verschillende mooie wandelingen gemaakt en lekkere sla met vis gegeten.",
    "Filmavonden in bed en ik die telkens tegen de slaap vecht! Mind your language is op jouw lijf geschreven.",
    "Jij die de film iedere keer aan mij moet uitleggen omdat ik hem niet begrijp.",
    "Wij die elkaar wakker duwen als we een nachtmerrie hebben. Ik die dan tegen jou springt uit schrik.",
    "Jouw tenen sprijden",
    "mijn irritante buikobsessie",
    "Mijn vinger in jouw mond steken als je geeuwt.",
    "Miljoenen kusjes geven op je wangetje en nekje",
    "Jij die zo goed masseert.",
    "Ik die niet hard genoeg durf masseren om jou niet te breken",
    "Niemand praat jou in slaap zoals ik dat kan. Kometen en planeten.",
    "Fietsen in Bazel. Met de elektrische fiets vond je het zo leuk.",
    "Naar de luchtballonnen gaan zien in Sint-Niklaas.",
    "Wortelstoemp, met liefde gemaakt.",
    "Rondrit Nederland met Deltawerken.",
    "Spelletje bijten of blazen op de buik, drie vragen.",
    "Badminton op de parking van Colruyt of aan't Ster.",
    "Allebei in shock na het weekend met neven en nichten.",
    "Samen uitgaan met neven en nichten in Hanger 26.",
    "Naar Carré met Peter en Nasteha.",
    "Waterfietsen",
    "Kajakken op de Lilse Bergen.",
    "Aan de Bazelse Kreek gaan liggen.",
    "Kleine, flinke meid!",
    "Altijd een stap voor op mij.",
    "Samen beugel gedragen.",
    "Jouw eerste dag met de beugel. Jouw mond als je moest lachen.",
    "In de auto altijd hand in hand rijden.",
    "Samen rollen in bed.",
    "In Prinsstraat met bibberende benen van de trappen gaan...",
    "Samen tuinieren",
    "Jij kijkt in mijn ogen als je drinkt.",
    "Goed pijn. Maar pijn is toch niet goed?",
    "Naar de sterren kijken op het dak in de Prinsstraat",
    "We zijn een team.",
    "Ongeveer 4200 dagen en nachten samen geslapen, geleefd.",
    "'s Nachts pak ik jou lepeltje lepeltje wanneer je met koude billetjes van de wc terugkomt.",
    "Samen het Atomium bezocht. (Mmaar ook eens alleen :D)",
    "Sumaya de white washer expert",
    "Jouw kookkunsten",
    "Gas geven godverdomme!",
    "Sexy kleedje in Maasmechelen (Versace)",
    "Jij wil in mijn poep bijten.",
    "Samen sushi ontdekt in Kruibeke",
    "Staan de vuilbakken buiten??",
    "Je niet aanraken als ik kip heb gesneden :D."
]